SHOW TABLES;


SELECT 
    SUM(CASE WHEN AGENT_NAME IS NULL THEN 1 ELSE 0 END) AS Null_AGENT_NAME,
    SUM(CASE WHEN WORKING_AREA IS NULL THEN 1 ELSE 0 END) AS Null_WORKING_AREA,
    SUM(CASE WHEN COMMISSION IS NULL THEN 1 ELSE 0 END) AS Null_COMMISSION,
    SUM(CASE WHEN PHONE_NO IS NULL THEN 1 ELSE 0 END) AS Null_PHONE_NO,
    SUM(CASE WHEN COUNTRY IS NULL THEN 1 ELSE 0 END) AS Null_COUNTRY,
    SUM(CASE WHEN AGENT_CODE IS NULL THEN 1 ELSE 0 END) AS Null_AGENT_CODE
FROM agents;


DESCRIBE agents;
DESCRIBE customer;
DESCRIBE orders;

SELECT AGENT_NAME, AGENT_CODE, WORKING_AREA, COMMISSION, PHONE_NO, COUNTRY, COUNT(*) FROM agents
GROUP BY AGENT_NAME, AGENT_CODE, WORKING_AREA, COMMISSION, PHONE_NO, COUNTRY
HAVING COUNT(*) >1;

SELECT COUNT(ORD_NUM), SUM(ORD_AMOUNT), AVG(ORD_NUM) FROM orders 

SELECT a.AGENT_NAME, COUNT(c.CUST_NAME) FROM agents a JOIN customer c ON a.WORKING_AREA = c.WORKING_AREA
WHERE c.GRADE = 3
GROUP BY a.AGENT_NAME
ORDER BY COUNT(c.CUST_NAME) DESC
LIMIT 1;

SELECT
    a.AGENT_NAME,
    COUNT(*) AS high_grade_customer_count
FROM customer c
JOIN agents a ON c.AGENT_CODE = a.AGENT_CODE
WHERE c.GRADE = 3
GROUP BY a.AGENT_NAME
ORDER BY high_grade_customer_count DESC
LIMIT 1;

SELECT c.CUST_CITY, SUM(o.ORD_AMOUNT) as total_order_amount FROM customer c JOIN orders o ON c.CUST_CODE = o.CUST_CODE
GROUP BY c.CUST_CITY
ORDER BY SUM(o.ORD_AMOUNT) DESC
LIMIT 3;

SELECT COUNT(CUST_NAME) FROM customer


SELECT
    c.CUST_NAME,
    SUM(o.ORD_AMOUNT) AS total_order_value
FROM orders o
JOIN customer c ON o.CUST_CODE = c.CUST_CODE
GROUP BY c.CUST_NAME
ORDER BY total_order_value DESC;

SELECT
    ROUND((COUNT(DISTINCT CASE WHEN order_count > 1 THEN CUST_CODE END) / COUNT(DISTINCT CUST_CODE)) * 100, 2) AS repeat_customer_percentage
FROM (
    SELECT CUST_CODE, COUNT(*) AS order_count
    FROM orders
    GROUP BY CUST_CODE
) AS customer_orders;

SELECT c.CUST_COUNTRY, MAX(c.OUTSTANDING_AMT) FROM customer
GROUP BY c.CUST_COUNTRY